sudo: true
dist: trusty
cache: false
env:
  matrix:
  - URL=https://developer.salesforce.com/media/salesforce-cli/sfdx-linux-amd64.tar.xz
  global:
    secure: bCWpXHoPaDaFrd9HdwXTgNMJGhCRHn2Msezd4VoPveAUFh6C5a5moSTOm47TFHJFrJPIQXoRRB9+XHOmrxqvIxofNnMATb90id4YoBJogN1bFMzltgro7qC0T1Q31Eu4pZ5JDXJwRuj9q94x6ithjUUHv0uqBf2YgBMB4Z36dtJ6dN88XfqPE4pY8Sbz0fE/rrCNYzuGSpOQH8IRzFVxbjE67H93mld3dmhbN7+FXrM4gaCvywyKV5hnC/WqxdKbhnsXSV6787fmVtu/HlrZ9qk51Ta756kYbPSeoDBQq0BXNZ25Q+RM2CiEadBm+ehqNZpANuq/l8unOlUdBCG9cnFir1HLGi2pYsjCo5m/v82PpOKvGCnzJZG6ksdMBpa8N7ODiivMpTtcFlnK6/b1GuqOR2yglOyRzfPIa2RjGevWGG3qpq6g/ICFbRH+HEnxK67kA2wpfMaASjF+NmeUNbUUSHZdJrLO0rK1CXY3yLT9FANyFvNpSCWyrpaa05LqW76WpYiBmo7ombInbJGsHlbv9M+SCDPlisk7P67VSOu7v2P0eFSWRNFAAz/1n0iV6HruQhTYNLT8IurKTD35DT5qMQ6aBXx4HSdik5uxKdhEpIFPb1wydEmlcPl/gx8QURuYOfEUQNbV94sJpb6s36N97mPxggNuLrxY1RjKEUk=
before_install:
- export SFDX_AUTOUPDATE_DISABLE=true
- export SFDX_USE_GENERIC_UNIX_KEYCHAIN=true
- export SFDX_DOMAIN_RETRY=300
- wget -qO- $URL | tar xJf -
- "./sfdx/install"
- export PATH=./sfdx/$(pwd):$PATH
- sfdx update
- sfdx --version
- sfdx plugins --core
- sfdx force:auth:jwt:grant --clientid $CONSUMERKEY --jwtkeyfile assets/server.key
  --username $USERNAME --setdefaultdevhubusername -a myTPO
script:
- sfdx force:org:create -v myTPO -s -f config/project-scratch-def.json -a ciorg
- sfdx force:source:push -u ciorg
- sfdx force:apex:test:run -u ciorg -c -r human
- sfdx force:org:delete -u ciorg -p
